# Generated by Django 4.2.3 on 2023-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField()),
                ('report', models.TextField()),
                ('fare', models.TextField()),
                ('summary', models.TextField(default='this is summary, which is cool!')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
