# Generated by Django 4.2.3 on 2023-07-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetails_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='Product',
        ),
    ]
