# Generated by Django 4.2.3 on 2023-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='product',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=120),
        ),
    ]
