# Generated by Django 4.2.3 on 2023-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_fare_alter_product_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
