# Generated by Django 4.2.3 on 2023-07-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='version',
            new_name='prominent',
        ),
    ]
