# Generated by Django 4.2.3 on 2023-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prominent',
            field=models.BooleanField(default=True),
        ),
    ]
